const steps = [
  {
    number: "01",
    title: "One question",
    description: "Each episode starts with an urgent or important question — from politics, sport, or current affairs. ",
  },
  {
    number: "02",
    title: "Two perspectives",
    description: "Sandalwood & Sage make their strongest cases For and Against, drawing on research, data, and reasoned argument.",
  },
  {
    number: "03",
    title: "You decide",
    description: "Weigh up the arguments and facts and decide not just what you think, but why you think it.",
  },
];

const credo = [
  "Democratic citizenship thrives on deliberation.",
  "Deliberation is the process of generative debate.",
  "Deliberation serves democracy when it is easily accessible.",
  "Generative debate is a process of discovery through argument.",
  "We build Arguments by organising evidence.",
  "We communicate clearly so that they are easily accessible.",
  "We make our Arguments and Judgements transparently.",
  "We listen attentively to other points of view.",
  "We look for common ground even if there's not much of it to be found.",
  "We sometimes change our minds.",
];

const HowItWorks = () => (
  <section id="how-it-works" className="mx-auto max-w-4xl px-5 py-8 sm:py-10">
    <p className="text-[11px] sm:text-xs font-medium uppercase tracking-[0.18em] text-section-label mb-2">
      How it Works
    </p>
    <h2 className="text-2xl sm:text-3xl text-foreground mb-6 sm:mb-8 leading-tight">
      Argue. Substantiate. Listen. Evolve.
    </h2>
    <div className="grid gap-3 sm:gap-4 md:grid-cols-3">
      {steps.map((step) => (
        <div key={step.number} className="rounded-xl border bg-card p-5 sm:p-6">
          <span className="text-xs font-semibold text-primary tracking-[0.14em]">
            {step.number}
          </span>
          <h3 className="mt-2.5 text-lg text-card-foreground leading-snug">{step.title}</h3>
          <p className="mt-1.5 text-sm text-muted-foreground leading-relaxed">{step.description}</p>
        </div>
      ))}
    </div>

    <div className="mt-8 sm:mt-10 grid gap-6 md:grid-cols-2">
      <div className="flex flex-col">
        <p className="text-[11px] sm:text-xs font-medium uppercase tracking-[0.18em] text-section-label mb-2">
          Our Credo
        </p>
        <h3 className="font-serif text-2xl sm:text-3xl text-foreground mb-4 sm:mb-5 leading-tight">
          What we believe.
        </h3>
        <div className="rounded-xl border bg-card p-5 sm:p-7 flex-1">
          <ul className="space-y-2.5">
            {credo.map((line, i) => (
              <li
                key={i}
                className="flex gap-3 text-sm sm:text-[0.95rem] text-card-foreground leading-relaxed"
              >
                <span className="mt-[0.55rem] h-1.5 w-1.5 shrink-0 rounded-full bg-primary" aria-hidden />
                <span>{line}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div className="flex flex-col">
        <p className="text-[11px] sm:text-xs font-medium uppercase tracking-[0.18em] text-section-label mb-2">
          How we do it
        </p>
        <h3 className="font-serif text-2xl sm:text-3xl text-foreground mb-4 sm:mb-5 leading-tight">
          Credits & tools.
        </h3>
        <div className="rounded-xl border bg-card p-5 sm:p-7 flex-1">
          <ul className="space-y-2.5 text-sm sm:text-[0.95rem] text-card-foreground leading-relaxed">
            <li><span className="text-muted-foreground">Published by </span>The Four Ashes Publishing Limited</li>
            <li><span className="text-muted-foreground">Content created by </span>Gareth Cadwallader</li>
            <li><span className="text-muted-foreground">Research assistance by </span>Google Gemini and Claude.AI</li>
            <li><span className="text-muted-foreground">Dialog editing by </span>Notebook LM</li>
            <li><span className="text-muted-foreground">Sandalwood &amp; Sage images by </span>Heygen</li>
            <li><span className="text-muted-foreground">Sandalwood &amp; Sage voices by </span>ElevenLabs v3</li>
            <li><span className="text-muted-foreground">Video generated by </span>Jogg.AI</li>
          </ul>
        </div>
      </div>
    </div>
  </section>
);

export default HowItWorks;
